config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles #only: [:show, :index, :new, :edit, :create, :update, :destroy]
  get 'signup', to: 'users#new'
  #post 'users', to: 'users#create'
  resources :users, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    validates :title, presence: true, length: { minimum:6, maximum: 100 }
    validates :description, presence: true, length: { minimum:10, maximum: 300 }
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    has_many :articles
    validates :username, presence: true, uniqueness: { case_sensitive: false }, length:{minimum: 3, maximum: 25}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, uniqueness: { case_sensitive: false }, length:{ maximum: 105 }, format: { with: VALID_EMAIL_REGEX }
    has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]

    def show 
        

        #@article = Article.find(params[:id])

    end
    def index 
        @articles = Article.paginate(page: params[:page], per_page: 5)

    end

    def new

        @article = Article.new
    end

    def edit 

        #@article = Article.find(params[:id])

    end


    def create
        #render plain: params[:article]
        @article = Article.new(article_params)
        @article.user = User.first
        #@article.save
        #redirect_to article_path(@article)
        if @article.save
            flash[:notice] = "Article was created successfully"
            redirect_to @article
        else
            render 'new'
        end
        #render plain: @article.inspect

    end
    def update 
        #@article = Article.find(params[:id])
        if @article.update(article_params)
            flash[:notice] = "Article was updated successfully"
            redirect_to @article
        else
            render 'edit'

        end

    end
    def destroy
        #@article = Article.find(params[:id])
         @article.destroy
         redirect_to articles_path

    end

    private

    def set_article
        @article = Article.find(params[:id])
    end

    def article_params
        params.require(:article).permit(:title, :description)
    end



end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home 
    end

    def about 
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def show
        @user = User.find(params[:id])
        @articles = @user.articles.paginate(page: params[:page], per_page: 5)

    end

    def index
        @users = User.paginate(page: params[:page], per_page: 5)

    end

    def new
        @user = User.new
    end

    def edit
        @user = User.find(params[:id])
    end

    def update 
        @user = User.find(params[:id])
        if @user.update(user_params)
            flash[:notice] = "Your account information is successfully updated "
            redirect_to @user

        else
            render 'edit'
        end
    end

    def create
        @user = User.new(user_params)
        if @user.save
            flash[:notice] = "Welcome to the alpha Blog #{@user.username}, you have successfully signed up"
            redirect_to articles_path
        else
            render 'new'
        end

    end

    private
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, options = { size: 80})
        email_address = user.email.downcase
        hash = Digest::MD5.hexdigest(email_address)
        size = options[:size]
        gravatar_url =  "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block") 
    end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class= "container">
<% @articles.each do |article| %>
		<div class="row justify-content-md-center">
			<div class = "col-8 mt-4">

			<div class="card text-center shadow mb-5 bg-white rounded">
					<div class="card-header font-italic">
					   <% if article.user %>	
						 by <%= link_to article.user.username, user_path(article.user) %>
					   <%end %>>
					</div>
					<div class="card-body">
						<h5 class="card-title "><%= link_to article.title, article_path(article), class: "text-success" %></h5>
						<p class="card-text"><%= truncate(article.description, lenth: 100) %></p>
						<%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
						<%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
						<%= link_to "Delete", article_path(article), class: "btn btn-outline-danger", method: :delete, data: {confirm: " Are you sure ?"} %>
						<!--<a href="#" class="btn btn-outline-success"> View </a>
						<a href="#" class="btn btn-outline-info">Edit</a>
						<a href="#" class="btn btn-outline-danger">Delete</a>-->
					</div>
				<div class="card-footer text-muted">
					<small> Created <%= time_ago_in_words(article.created_at) %> ago,
					edited <%= time_ago_in_words(article.updated_at) %></small>
				</div>
			</div>
		</div>
	</div>
</div>
<% end %>

app/views/articles/_form.html.erb
<div class= "container" >

 <!--this is added in shared forder 
  <% if @article.errors.any? %>
    <h2>THe following errors preventing the article from being saved</h2>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  <% end %>-->
  <div class= "row justify-content-center ">
    <div class="col-10">
      <%= render 'shared/errors', obj: @article %>
      <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class= "form-group-row">
          <%= f.label:title, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
          
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Article" %>
          </div>
        </div>
      <div class= "form-group-row">
        <%= f.label:description, class: "col-2 col-form-label text-light" %>
        <div class="col-10">
        <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description" %>

        </div>
      </div>
      <div class= "form-group-row text-center">

        <%= f.submit class: "btn-btn-outline-light btn-lg" %>
      </div>

      <% end %>
    </div>
    <div class= "form-group-row text-center">
    <div class="mb-3">  
      <%= link_to '[ Cancel and Return to Article listing ]', articles_path, class: "text-info" %>
    </div>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4" >Edit article</h1>


<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4 "> Listing all the Articles </h1>

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>
<%= render 'article' %>
<div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
</div>



<!--<table>
	<thead>
		<tr>
			<th>Title</th>
			<th>Description</th>
			<th colspan="3">Actions</th>
		</tr>
	</thead>
	<tbody>
		<% @articles.each do |article| %>
		<tr>
			
			<td><%= article.title %></td>
			<td><%= article.description %></td>
			<td><%= link_to 'Show', article_path(article) %></td>
			<td><%= link_to 'Edit', edit_article_path(article) %></td>
			<td><%= link_to 'Delete', article_path(article), method: :delete, data: { Confirm: "Are you sure?"} %></td>
		</tr>
		<% end %>
	</tbody>

</table>
<p>
<%= link_to 'Create new Article', new_article_path %>
</p>-->

app/views/articles/new.html.erb
<h1 class="text-center mt-4", placeholder="New Article" >Create a new article</h1>

<%= render 'form' %>

<!-- <%= link_to 'Return to Article listing', articles_path %>-->

app/views/articles/show.html.erb
<h2 class="text-center mt-4 "><%= @article.title %></h2>
<div class= "container">

		<div class="row justify-content-md-center">
			<div class = "col-8 mt-4">

			<div class="card text-center shadow mb-5 bg-white rounded">
					<div class="card-header font-italic">
						By <%= @article.user.username if @article.user %>
						<%= link_to gravatar_for(@article.user), user_path(@article.user) %>
					</div>
					<div class="card-body">

						<div class="card-text text-start"><%= simple_format(@article.description) %></div>
		
						<%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
						<%= link_to "Delete", article_path(@article), class: "btn btn-outline-danger", method: :delete, data: {confirm: " Are you sure ?"} %>
						<!--<a href="#" class="btn btn-outline-success"> View </a>
						<a href="#" class="btn btn-outline-info">Edit</a>
						<a href="#" class="btn btn-outline-danger">Delete</a>-->
					</div>
				<div class="card-footer text-muted">
					<small> Created <%= time_ago_in_words(@article.created_at) %> ago,
					edited <%= time_ago_in_words(@article.updated_at) %></small>
				</div>
			</div>
		</div>
	</div>
</div>














<!--before changing into seperate article this code was here lecture 120..

    <h1> Showing articles details now </h1>

<p><strong>Title: </strong><%= @article.title %></p>

<p><strong>Description: </strong><%= @article.description %></p> 

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Delete', article_path(@article) , method: :delete, data: { Confirm: "Are you sure?"} %>  |
<%= link_to 'Return to Article listing', articles_path %>-->

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white-50">
    <div class="container text-center">
      <small>Copyright &copy; Raj Verma</small>
    </div>
</footer>

app/views/layouts/_messages.html.erb
    <% flash.each do |name, msg| %>
     <div class="alert alert-success alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
     </div>
    <% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
  
    <%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
       
        <li class="nav-item">
          
          <%= link_to "Bloggers", users_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to "Create new article", new_article_path, class: "dropdown-item" %></li>
            <li><%= link_to "View articles", articles_path, class: "dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1> This is about page you are seeing <h1>

<%= link_to 'Articles listing', articles_path %> | 
<%= link_to 'Home page', root_path %>

app/views/pages/home.html.erb
<div class=" container" id="home-container">
    <div class="jumbotron text-center text-white">
    <h1 class="display-4">Alpha Blog</h1>
    <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
    <hr class="my-4">
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <p class="lead">
       <!-- <a class="btn btn-success btn-lg" href="#" role="button">Sign Up!</a>-->
        <%= link_to"Sign Up!", signup_path, class: "btn btn-success btn-lg" %>
    </p>
    </div>
</div>

<%= link_to 'Articles listing', articles_path %>
<%= link_to 'About Path', about_path %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <h4 class="alert-heading">The following errors preventing the <%= obj.class.name.downcase %> from being saved!</h4>
        <ul>
            <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul> 
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<% end %>

app/views/users/_form.html.erb
<div class= "container" >

  <div class= "row justify-content-center ">
    <div class="col-10">
      <%= render 'shared/errors', obj: @user %>
      <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class= "form-group-row">
          <%= f.label :username, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
          
            <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter user name" %>
          </div>
        </div>
      <div class= "form-group-row">
        <%= f.label :email, class: "col-2 col-form-label text-light" %>
        <div class="col-10">
        <%= f.email_field :email,  class: "form-control shadow rounded", placeholder: "Enter your email" %>

        </div>
      </div>

      <div class= "form-group-row">
        <%= f.label :password, class: "col-2 col-form-label text-light" %>
        <div class="col-10">
        <%= f.password_field :password,  class: "form-control shadow rounded", placeholder: "Choose your password" %>

        </div>
      </div>

      <div class= "form-group-row text-center">

        <%= f.submit(@user.new_record? ?  "Sign Up" : "Update account", class: "btn-btn-outline-light btn-lg") %>
      </div>

      <% end %>
    </div>
    <div class= "form-group-row text-center">
    <div class="mb-3">  
      <%= link_to '[ Cancel and Return to Article listing ]', articles_path, class: "text-info" %>
    </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit your profile</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4"> Alpha Bloggers</h1>

<div class="flickr_pagination">
    <%= will_paginate @users, :container => false %>
</div>

<div class= "container">
<% @users.each do |user| %>
		<div class="row justify-content-md-center">
			<div class = "col-8 mt-4">

			<div class="card text-center shadow mb-5 bg-white rounded">
					<div class="card-header font-italic">
						 <%= link_to user.username, user %>
					</div>
					<div class="card-body">
						<h5 class="card-title ">
							<%= link_to gravatar_for(user,size: 150), user %>
						</h5>
						<p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
						<%= link_to "View profile", user, class: "btn btn-outline-success" %>
						<%= link_to "Edit profile", edit_user_path(user), class: "btn btn-outline-info" %>
						
						<!--<a href="#" class="btn btn-outline-success"> View </a>
						<a href="#" class="btn btn-outline-info">Edit</a>
						<a href="#" class="btn btn-outline-danger">Delete</a>-->
					</div>
				<div class="card-footer text-muted">
					<small> Joined <%= time_ago_in_words(user.created_at) %> ago</small>
				</div>
			</div>
		</div>
	</div>
</div>
<% end %>

<div class="flickr_pagination mb-4 ">
    <%= will_paginate @articles, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4" >Sign Up Alpha Blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username %>'s profile</h1>

<%= gravatar_for @user, size: 200 %>

<div class="text-center" mt-4>
    <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info" %>
</div>

<h3 class="text-center mt-4">Articles</h3>

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article' %>

<div class="flickr_pagination mb-4 ">
    <%= will_paginate @articles, :container => false %>
</div>